// <auto-generated />
using System;
using Mango.Services.CouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.CouponAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231115152751_CouponToDb")]
    partial class CouponToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.CouponAPI.Model.Coupon", b =>
                {
                    b.Property<Guid>("couponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("coupon_id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("couponCode")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)")
                        .HasColumnName("coupon_code");

                    b.Property<double>("discountAmount")
                        .HasColumnType("float")
                        .HasColumnName("discount_amount");

                    b.Property<int>("minAmount")
                        .HasColumnType("int")
                        .HasColumnName("min_amount");

                    b.HasKey("couponId");

                    b.ToTable("Coupons");
                });
#pragma warning restore 612, 618
        }
    }
}
