// <auto-generated />
using System;
using Mango.Services.CouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.CouponAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.CouponAPI.Model.Coupon", b =>
                {
                    b.Property<Guid>("couponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("coupon_id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("couponCode")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)")
                        .HasColumnName("coupon_code");

                    b.Property<double>("discountAmount")
                        .HasColumnType("float")
                        .HasColumnName("discount_amount");

                    b.Property<int>("minAmount")
                        .HasColumnType("int")
                        .HasColumnName("min_amount");

                    b.HasKey("couponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            couponId = new Guid("d3986cd8-9e26-4603-ac49-3501be21adc6"),
                            couponCode = "20FF",
                            discountAmount = 20.0,
                            minAmount = 40
                        },
                        new
                        {
                            couponId = new Guid("87def2c8-b32a-4352-83ed-9339c6ef227a"),
                            couponCode = "40FF",
                            discountAmount = 40.0,
                            minAmount = 80
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
